version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_USER: development
      MYSQL_PASSWORD: development
      MYSQL_DATABASE: task_mate
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
